from pathlib import Path

root = Path(__file__).resolve().parent
p = root / 'index.html'
s = p.read_text(encoding='utf-8')
marker = '      <section class="soft" id="customers">'
vision = '''      <section id="vision-edge-public" style="background:#071a33;color:#fff">
        <div class="container">
          <div class="section-head"><span class="kicker" style="color:#79e1d5">VISION EDGE · HUMAN-REVIEWED SAFETY AI</span><h2>현장 카메라·센서의 위험 감지 후보를<br />사람 검토와 조치 증빙까지 연결합니다.</h2><p style="color:#d5e2f2">안전모·보호구 미착용, 제한구역 진입, 사람·차량 근접, 지게차 후진 유도자 미확인, 장내 차량 과속, 미승인 차량 진입, 고소작업 추락방호 미확인 등의 후보를 현장 규칙과 비교하고, 사람 확인 후 공식 안전사건과 후속조치 폐루프로 전환하는 제한형 Vision Edge 구조를 고도화하고 있습니다.</p></div>
          <div class="grid-4">
            <article class="card value-card"><b>01</b><h3>감지 + 현장 규칙</h3><p>카메라 탐지 결과를 구역별 PPE, 속도, 출입승인, 후진 유도자, 고소작업 규칙과 비교합니다.</p></article>
            <article class="card value-card"><b>02</b><h3>식별정보 최소수집</h3><p>사업장 차량·장비 자산번호 또는 승인 식별값은 마스킹·권한분리·해시·감사기록 원칙으로 처리합니다.</p></article>
            <article class="card value-card"><b>03</b><h3>사람 검토 후 사건화</h3><p>AI 감지 후보는 사람 확인 전 공식 위험 확정이나 자동 작업중지 명령으로 처리하지 않습니다.</p></article>
            <article class="card value-card"><b>04</b><h3>발주처 통제 KPI</h3><p>미종결·기한초과·반복위험·PPE·차량근접·사람확정률·조치완료율·재평가율을 다현장 관점에서 확인합니다.</p></article>
          </div>
          <div class="actions"><a class="btn btn-primary" href="/vision-edge.html">Vision Edge 기술 구조 보기</a><a class="btn btn-light" href="/use-cases/public/vision-edge.html">발주처·공공기관 적용 보기</a><a class="btn btn-light" href="/trust/vision-edge.html">신뢰·개인정보 원칙 보기</a></div>
          <div class="value-note">Vision Edge는 현재 제한형 파일럿·검증 범위입니다. 연속 원본영상의 무제한 클라우드 업로드, 자동 법적 판단, 자동 처벌 또는 사람 확인 없는 자동 작업중지를 전제로 하지 않습니다.</div>
        </div>
      </section>

'''
if 'id="vision-edge-public"' not in s:
    if marker not in s: raise SystemExit('HOME_MARKER_NOT_FOUND')
    s = s.replace(marker, vision + marker, 1)
    p.write_text(s, encoding='utf-8')

style='''<style>*{box-sizing:border-box}body{margin:0;color:#10233f;background:#f5f8fc;font:16px/1.7 -apple-system,BlinkMacSystemFont,"Noto Sans KR",sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1120px,calc(100% - 36px));margin:auto}.hero{padding:72px 0;background:linear-gradient(135deg,#061a33,#0a4f83);color:#fff}.badge{display:inline-flex;padding:8px 12px;border-radius:999px;background:#dff8f1;color:#08695c;font-weight:900}.hero h1{font-size:clamp(38px,6vw,64px);line-height:1.12;margin:16px 0}.hero p{max-width:860px;color:#dceafb;font-size:19px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:24px}.btn{display:inline-flex;min-height:48px;align-items:center;padding:0 18px;border-radius:999px;background:#fff;color:#061a33;font-weight:900}.btn.primary{background:#1680ea;color:#fff}.section{padding:62px 0}.head{max-width:860px}.head h2{font-size:clamp(30px,4vw,48px);line-height:1.2;margin:0 0 12px}.head p,.card p{color:#5d6e82}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:24px}.card{background:#fff;border:1px solid #d8e4f0;border-radius:18px;padding:22px}.card h3{margin:6px 0 8px}.flow{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:22px}.step{padding:15px;border-radius:14px;background:#071a33;color:#fff;font-weight:900;text-align:center}.notice{margin-top:20px;padding:18px;border:1px solid #b9ded7;background:#edf9f6;border-radius:16px}.dark{background:#071a33;color:#fff}.dark .card{background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.15)}.dark .card p{color:#d5e2f2}footer{padding:30px 0;background:#04152c;color:#c7d7e9}@media(max-width:760px){.grid,.flow{grid-template-columns:1fr}.hero{padding:50px 0}}</style>'''

(root/'vision-edge.html').write_text(f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>COREON Vision Edge | 사람 검토형 산업안전 영상 AI</title><meta name="description" content="현장 영상·이미지·짧은 클립의 위험 감지 후보를 현장 규칙, 사람 검토, 공식 사건, 조치·증빙·잔여위험 재평가까지 연결하는 COREON Vision Edge 제한형 파일럿 구조.">{style}</head><body><header class="hero"><div class="wrap"><span class="badge">COREON VISION EDGE · LIMITED PILOT</span><h1>영상 AI가 위험을 찾는 데서 끝나지 않고<br>조치가 끝날 때까지 연결합니다.</h1><p>COREON Vision Edge는 PPE 미착용, 제한구역 진입, 사람·차량 근접, 지게차 후진 유도자 미확인, 장내 과속, 미승인 차량 진입, 고소작업 추락방호 미확인 등의 감지 후보를 현장 규칙과 비교하고 사람이 확인한 뒤 Safety AX 폐루프로 전환합니다.</p><div class="actions"><a class="btn primary" href="https://app.coreon-global.com/vision-edge" target="_blank" rel="noopener">Vision Edge 검토화면</a><a class="btn" href="/use-cases/public/vision-edge.html">공공기관 적용</a><a class="btn" href="/trust/vision-edge.html">신뢰 원칙</a><a class="btn" href="/">홈으로</a></div></div></header><main><section class="section"><div class="wrap"><div class="head"><h2>감지 → 판정 → 식별 → 조치 → 증빙 → 재평가</h2><p>도로 단속의 자동 처벌 구조를 복제하는 것이 아니라, 산업현장 안전통제를 위해 감지 후보를 안전업무 사건으로 전환하는 구조입니다.</p></div><div class="flow"><div class="step">감지 후보</div><div class="step">현장 규칙</div><div class="step">식별·마스킹</div><div class="step">사람 검토</div><div class="step">조치·증빙</div><div class="step">잔여위험·승인</div></div></div></section><section class="section dark"><div class="wrap"><div class="head"><h2>현재 고도화된 탐지 사전</h2></div><div class="grid"><article class="card"><h3>PPE</h3><p>안전모·안전조끼·안전대·보안경 미착용 후보 및 이륜차 안전모 미착용 후보.</p></article><article class="card"><h3>구역·차량</h3><p>제한구역 진입, 사람·차량 근접, 장내 과속, 미승인 차량 진입 후보.</p></article><article class="card"><h3>행동성 위험</h3><p>지게차 후진 유도자 미확인, 고소작업 추락방호 미확인 등 짧은 클립 기반 행동 후보.</p></article></div></div></section><section class="section"><div class="wrap"><div class="head"><h2>식별정보는 안전조치 목적의 최소 범위로</h2></div><div class="grid"><article class="card"><h3>마스킹</h3><p>일반 화면에는 차량·장비 식별값을 마스킹해 표시합니다.</p></article><article class="card"><h3>권한 분리</h3><p>승인된 역할만 필요한 범위에서 원 식별값을 확인하도록 설계합니다.</p></article><article class="card"><h3>해시·감사로그</h3><p>식별값 매칭과 변경 이력은 해시 및 감사기록과 연결합니다.</p></article></div><div class="notice"><b>운영 경계</b><br>AI 감지 후보는 사람 검토 전 공식 위험 확정, 자동 법적 판단, 자동 처벌 또는 자동 작업중지 명령이 아닙니다. 실제 카메라 운영은 현장 승인·개인정보 처리 기준·파일럿 검증을 거쳐야 합니다.</div></div></section></main><footer><div class="wrap">주식회사 코레온홀딩스 · COREON Safety AX Agent · 0507-1358-1482 · contact@coreon-global.com</div></footer></body></html>''', encoding='utf-8')

pub=root/'use-cases'/'public';pub.mkdir(parents=True,exist_ok=True)
(pub/'vision-edge.html').write_text(f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>발주처·공공기관 Vision Edge | COREON</title><meta name="description" content="다현장·다협력사의 영상 감지 후보를 사람 검토, 조치증빙, 반복위험 KPI까지 연결하는 COREON 발주처·공공기관 Vision Edge 적용 구조.">{style}</head><body><header class="hero"><div class="wrap"><span class="badge">PRINCIPAL / PUBLIC VISION ASSURANCE</span><h1>발주처가 모든 CCTV를 보는 대신<br>조치가 필요한 예외를 확인합니다.</h1><p>현장별 카메라·센서 감지 후보를 그대로 중앙에 쌓는 것이 아니라, 사람 확인을 거친 공식 사건과 미종결·기한초과·반복위험·증빙누락 중심의 통제 KPI로 연결합니다.</p><div class="actions"><a class="btn primary" href="https://app.coreon-global.com/enterprise-public" target="_blank" rel="noopener">Enterprise/Public</a><a class="btn" href="/vision-edge.html">Vision Edge 구조</a><a class="btn" href="/use-cases/public/">공공기관 활용</a></div></div></header><main><section class="section"><div class="wrap"><div class="head"><h2>발주처·공공기관이 확인할 8개 KPI</h2></div><div class="grid"><article class="card"><h3>미종결·기한초과</h3><p>현장별 열린 위험과 후속업무 기한초과를 예외관리합니다.</p></article><article class="card"><h3>PPE·차량근접</h3><p>보호구 후보와 사람·차량 근접 위험을 구역·현장별로 봅니다.</p></article><article class="card"><h3>사람확정률</h3><p>AI 후보 중 현장 책임자가 실제 위험으로 확인한 비율을 분리합니다.</p></article><article class="card"><h3>조치완료율</h3><p>탐지 숫자보다 담당·기한·증빙이 닫힌 비율을 봅니다.</p></article><article class="card"><h3>재평가율</h3><p>조치 후 남은 위험이 다시 평가됐는지 확인합니다.</p></article><article class="card"><h3>반복위험</h3><p>같은 현장·구역·유형이 반복되는 패턴을 우선 확인합니다.</p></article></div><div class="notice">COREON은 기존 발주처·건설사·공공기관 시스템을 강제로 대체하기보다, 기존 기록과 현장 감지 결과 사이의 ‘실행·증빙 공백’을 연결하는 구조를 지향합니다.</div></div></section></main><footer><div class="wrap">COREON · 발주처·공공기관 도입상담 0507-1358-1482</div></footer></body></html>''', encoding='utf-8')

trust=root/'trust';trust.mkdir(exist_ok=True)
(trust/'vision-edge.html').write_text(f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vision Edge 신뢰·개인정보 원칙 | COREON</title><meta name="description" content="COREON Vision Edge의 사람 검토, 최소수집, 마스킹, 권한분리, 감사로그, 제한형 파일럿 원칙.">{style}</head><body><header class="hero"><div class="wrap"><span class="badge">VISION EDGE TRUST BOUNDARY</span><h1>AI가 보았다는 이유만으로<br>사람을 확정하거나 처벌하지 않습니다.</h1><p>COREON Vision Edge의 목적은 자동 처벌이 아니라 산업안전 조치와 이력관리입니다. 감지 후보는 사람 검토 전 공식 기록이 아니며, 식별정보는 필요한 범위로 제한합니다.</p><div class="actions"><a class="btn primary" href="/vision-edge.html">기술 구조</a><a class="btn" href="/trust/">COREON Trust</a><a class="btn" href="/">홈으로</a></div></div></header><main><section class="section"><div class="wrap"><div class="grid"><article class="card"><h3>Human-in-the-loop</h3><p>사람 확인 없이 공식 위험 확정·자동 법적 판단·자동 처벌을 수행하지 않습니다.</p></article><article class="card"><h3>최소수집</h3><p>연속 원본영상의 무제한 클라우드 업로드를 기본 전제로 하지 않고 스냅샷·짧은 클립 중심으로 검증합니다.</p></article><article class="card"><h3>식별정보 통제</h3><p>차량·장비 식별값은 마스킹·권한분리·해시·감사기록 원칙으로 취급합니다.</p></article><article class="card"><h3>Shadow Mode</h3><p>파일럿 단계에서는 자동 작업중지나 설비 제어 없이 감지 성능과 사람 검토 결과를 먼저 측정합니다.</p></article><article class="card"><h3>False Positive 관리</h3><p>확인·기각 결과를 분리하고 사람의 검토 결과로 성능지표를 관리합니다.</p></article><article class="card"><h3>현장 승인</h3><p>실제 카메라 연결은 현장 승인, 개인정보 처리 기준, 장비·네트워크 검증을 거쳐 제한적으로 활성화합니다.</p></article></div></div></section></main><footer><div class="wrap">COREON TRUST & EVIDENCE · 0507-1358-1482</div></footer></body></html>''', encoding='utf-8')

sp=root/'sitemap.xml';sm=sp.read_text(encoding='utf-8')
for u in ['https://www.coreon-global.com/vision-edge.html','https://www.coreon-global.com/use-cases/public/vision-edge.html','https://www.coreon-global.com/trust/vision-edge.html']:
    if u not in sm: sm=sm.replace('</urlset>',f'<url><loc>{u}</loc></url>\n</urlset>')
sp.write_text(sm,encoding='utf-8')
(root/'docs'/'v27.56-safety-ax-vision-expansion.md').write_text('''# v27.56 Safety AX Vision Expansion\n\n- Preserve the public/principal-sector hero and organization targeting.\n- Add Vision Edge as supporting technical proof, not a replacement hero message.\n- Add public Vision Edge, principal/public Vision Edge, and Vision Edge trust pages.\n- Position detection as human-reviewed candidates connected to corrective action, evidence and residual-risk reassessment.\n- State shadow-mode, minimum-data, masking and no-autonomous-stop boundaries.\n''',encoding='utf-8')
print('v27.56 landing patch applied')
