'use strict';
const assert=require('assert');
const fs=require('fs');
const ko=fs.readFileSync('serious-accident-compliance.html','utf8');
const en=fs.readFileSync('en/serious-accident-compliance.html','utf8');
const home=fs.readFileSync('en/index.html','utf8');
const sitemap=fs.readFileSync('sitemap.xml','utf8');
const cnt=(h,s)=>(h.match(new RegExp(`data-status="${s}"`,'g'))||[]).length;
for(const s of ['op','pa','cu']) assert.strictEqual(cnt(en,s),cnt(ko,s),`KO/EN status parity: ${s}`);
const seq=h=>[...h.matchAll(/data-status="(\w+)"/g)].map(m=>m[1]).join(',');
assert.strictEqual(seq(en),seq(ko),'KO/EN row order and status must match');
assert(en.includes('not legal advice')&&en.includes('exemption from liability'),'EN legal boundary missing');
assert(en.includes('Korean statutory text governs'),'EN translation boundary missing');
assert(en.includes('hreflang="ko"')&&ko.includes('hreflang="en"'),'hreflang pair missing');
assert(home.includes(`<b>${cnt(en,'op')}</b><span>Supported</span>`)&&home.includes(`<b>${cnt(en,'pa')}</b><span>Partial</span>`)&&home.includes(`<b>${cnt(en,'cu')}</b><span>Customer-performed / Roadmap</span>`),'EN home counts mismatch');
assert(home.includes('href="/en/serious-accident-compliance.html"'),'EN home link missing');
assert(sitemap.includes('https://www.coreon-global.com/en/serious-accident-compliance.html</loc>'),'EN sitemap entry missing');
for(const bad of ['100% mapped','fully compliant','guarantees compliance','ISO 45001 certified']) assert(!en.includes(bad)&&!home.includes(bad),`overclaim: ${bad}`);
console.log('PASS EN compliance mapping parity with KO, boundaries, home and sitemap');
